---
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended
plugins:
  - react
  - jsx-a11y
parserOptions:
  ecmaVersion: 8
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  # Possible Error
  no-await-in-loop: error
  no-dupe-else-if: error
  no-import-assign: error
  no-setter-return: error
  no-template-curly-in-string: warn
  # Best Practices
  block-scoped-var: error
  class-methods-use-this: warn
  curly: error
  default-case: warn
  default-param-last: warn
  dot-location:
    - warn
    - property
  dot-notation: warn
  eqeqeq:
    - error
    - smart
  grouped-accessor-pairs: error
  guard-for-in: warn
  max-classes-per-file: error
  no-alert: warn
  no-caller: error
  no-case-declarations: error
  no-constructor-return: error
  no-empty-function: error
  no-eval: error
  no-extra-bind: warn
  no-extra-label: error
  no-fallthrough: warn
  no-floating-decimal: error
  no-global-assign: error
  no-implicit-coercion: error
  no-implicit-globals: error
  no-implied-eval: error
  no-invalid-this: error
  no-iterator: warn
  no-labels: warn
  no-lone-blocks: error
  no-loop-func: error
  no-multi-spaces: warn
  no-new: warn
  no-new-func: error
  no-new-wrappers: error
  no-octal: warn
  no-octal-escape: warn
  no-proto: error
  no-return-await: warn
  no-script-url: warn
  no-self-assign: error
  no-self-compare: error
  no-sequences: error
  no-throw-literal: error
  no-unmodified-loop-condition: warn
  no-unused-expressions: warn
  no-useless-call: error
  no-useless-concat: error
  no-useless-return: error
  no-void: error
  no-warning-comments: warn
  prefer-promise-reject-errors: error
  require-await: error
  wrap-iife:
    - error
    - inside
  yoda: warn
  # Variables
  init-declarations: error
  no-label-var: error
  no-shadow: warn
  no-shadow-restricted-names: error
  no-undef: error
  no-undef-init: error
  no-undefined: error
  no-use-before-define: error
  # Stylistic Issues
  array-bracket-spacing: warn
  brace-style: error
  camelcase: warn
  comma-dangle: error
  comma-spacing: error
  comma-style: error
  eol-last: error
  func-call-spacing: error
  func-name-matching: error
  func-names:
    - error
    - never
  func-style:
    - error
    - declaration
    - allowArrowFunctions: true
  implicit-arrow-linebreak:
    - error
    - beside
  indent:
    - error
    - 2
  key-spacing: warn
  keyword-spacing: error
  lines-between-class-members: error
  max-depth: error
  max-len:
    - warn
    - code: 100
      ignoreUrls: true
  max-lines-per-function: warn
  max-nested-callbacks: error
  max-statements-per-line: error
  multiline-ternary:
    - error
    - always-multiline
  new-cap: error
  new-parens: error
  newline-per-chained-call:
    - error
    - ignoreChainWithDepth: 2
  no-array-constructor: warn
  no-lonely-if: warn
  no-multiple-empty-lines: warn
  no-nested-ternary: error
  no-tabs: warn
  no-trailing-spaces: warn
  no-unneeded-ternary: warn
  object-curly-spacing:
    - error
    - always
  object-property-newline:
    - error
    - allowAllPropertiesOnSameLine: false
  semi: error
  semi-spacing: error
  semi-style: error
  # React
  react/prop-types: off
env:
  node: true
  es6: true
  browser: true
