branches:
  only:
    - master
    - staging
deploy:
  provider: s3
  access_key_id: "${AWS_ACCESS_KEY_ID}"
  secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  bucket: "umdfacilitieslawsuit.dbknews.com"
  local_dir: build
after_deploy:
  - echo "Static site deployed"